### ISSUE TITLE
Feature Request: Credentials as env variables

### ISSUE THREAD

**Issue by WantStuff** [peter-mount/opendatabridge#1]
Not an issue, but a feature request.

Please could 'credentials as environment variables' be added? 
This would allow credentials to be be moved out of `config.xml` (and out of source control) and centralised into a vault or .env file.

Potential usage example:

### .env
```
MY_NRE_USER_NAME=me@somewhere.com
MY_NRE_PASSWORD=s00perSecr3t
MY_RMQ_USER_NAME=guest
MY_RMQ_PASSWORD=notAguest
```
### docker-compose.yml
```
services:
  openraildata:
    environment:
      - NRE_USERNAME=${MY_NRE_USER_NAME}
      - NRE_PASSWORD=${MY_NRE_PASSWORD}
      - RABBITMQ_USERNAME=${MY_RMQ_USER_NAME}
      - RABBITMQ_PASSWORD=${MY_RMQ_PASSWORD}
```

Thanks!
